baseURL = "https://robertbasement.github.io/hugoSite/"

theme = 'hola'
relativeURLs = true

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

[permalinks]
blog = "/blog/:filename/"


